### ISSUE TITLE
Increase project maintainability 

### ISSUE THREAD

**Issue by alexander-demicev** [rancher/aks-operator#107]
This epic will track tasks for increasing project maintainability:

- [x] Enable github workflows for this repository
- [x] Add golang-ci lint workflow
- [x] #108
- [x] Add new task to makefile for building operator binary
- [x] Create Azure services mocks to use for unit tests
- [x] Set up a basic unit test suite
- [x] Cover Azure services interactions with unit tests
- [x] #109
- [x] #110
- [x] Create a setup for running E2E tests
- [x] Start adding E2E tests
- [x] #111
- [x] #112
